/**
 * Names that come from the NewGRF data rather than from the UI. The dictionaries are
 * generated by pipeline/extract_firs_ru.py from the translation players actually run
 * (vendor/firs-ru) and from the game's own locale for names FIRS leaves to the game —
 * edit those sources, not the JSON. Cargos are keyed by id, not by label: WOOD is both
 * vanilla "wood" (Древесина) and FIRS "logs" (Брёвна).
 */
import { cargoByLabel } from '../dataset';
import { LOCALES, useLocaleStore, type Locale } from '../state/localeStore';
import cargosRu from './cargos.ru.json';
import industriesRu from './industries.ru.json';

const CARGO_NAMES: Record<string, Record<string, string>> = { ru: cargosRu.names };
const CARGO_UNITS: Record<string, Record<string, string>> = { ru: cargosRu.units };
const INDUSTRY_NAMES: Record<string, Record<string, string>> = { ru: industriesRu };

/** Translated cargo name, or the English one from the data. */
export function cargoName(cargo: { id: string; name: string } | null | undefined): string {
  if (!cargo) return '';
  const { locale } = useLocaleStore.getState();
  return CARGO_NAMES[locale]?.[cargo.id] ?? cargo.name;
}

/** Unit of measure the data spells out in words: litres, tonnes, crates… */
export function cargoUnits(units: string | null | undefined): string {
  if (!units) return '';
  const { locale } = useLocaleStore.getState();
  return CARGO_UNITS[locale]?.[units] ?? units;
}

/** Industry name; economies may rename an industry, hence the optional override. */
export function industryName(
  industry: { id: string; name: string; name_by_economy?: Record<string, string> } | null | undefined,
  economyId?: string,
): string {
  if (!industry) return '';
  const { locale } = useLocaleStore.getState();
  const translated = INDUSTRY_NAMES[locale]?.[industry.id];
  if (translated) return translated;
  return (economyId ? industry.name_by_economy?.[economyId] : undefined) ?? industry.name;
}

/**
 * Passengers and mail head every cargo list in the game itself, so they stay
 * pinned to the top instead of falling wherever the alphabet puts them.
 */
const PINNED_CARGOS = ['passengers', 'mail'];

/**
 * Cargo pickers read as a list, so order them by what the user actually sees.
 * Takes the locale as an argument rather than reading the store: callers memoise
 * the sorted list, and this way the locale is a real dependency of that memo.
 */
export function sortCargos<T extends { id: string; name: string }>(
  cargos: T[],
  locale: Locale,
): T[] {
  const names = CARGO_NAMES[locale] ?? {};
  const collator = new Intl.Collator(LOCALES[locale].numbers);
  const rank = (id: string) => {
    const pinned = PINNED_CARGOS.indexOf(id);
    return pinned === -1 ? PINNED_CARGOS.length : pinned;
  };
  return [...cargos].sort(
    (a, b) =>
      rank(a.id) - rank(b.id) ||
      collator.compare(names[a.id] ?? a.name, names[b.id] ?? b.name),
  );
}

/**
 * Node labels in the FIRS chain graph. A graphviz node id is either a cargo label
 * (ACID) or an industry id (coal_mine); cargo labels are resolved to a cargo id
 * through the dataset. Anything unknown keeps its English label.
 */
export function localiseDot(dot: string): string {
  const { locale } = useLocaleStore.getState();
  const cargos = CARGO_NAMES[locale] ?? {};
  const industries = INDUSTRY_NAMES[locale] ?? {};
  if (!Object.keys(cargos).length && !Object.keys(industries).length) return dot;
  const translate = (id: string) => {
    const cargo = cargoByLabel.get(id);
    return (cargo ? cargos[cargo.id] : undefined) ?? industries[id];
  };
  return dot.replace(/"([^"]+)" \[([^\]]*?)label="([^"]*)"/g, (full, id, attrs) => {
    const name = translate(id);
    return name ? `"${id}" [${attrs}label="${name}"` : full;
  });
}
