/**
 * Names that come from the NewGRF data rather than from the UI. The dictionaries are
 * generated by pipeline/extract_firs_ru.py from the translation players actually run
 * (vendor/firs-ru) and from the game's own locale for names FIRS leaves to the game —
 * edit those sources, not the JSON. Cargos are keyed by id, not by label: WOOD is both
 * vanilla "wood" (Древесина) and FIRS "logs" (Брёвна).
 */
import { cargoByLabel } from '../dataset';
import type { TrainSet } from '../engine/settings';
import { LOCALES, useLocaleStore, type Locale } from '../state/localeStore';
import cargosRu from './cargos.ru.json';
import industriesRu from './industries.ru.json';
import railtypesRu from './railtypes.ru.json';
import { t } from './index';

const CARGO_NAMES: Record<string, Record<string, string>> = { ru: cargosRu.names };
const CARGO_UNITS: Record<string, Record<string, string>> = { ru: cargosRu.units };
const INDUSTRY_NAMES: Record<string, Record<string, string>> = { ru: industriesRu };
// одна карта лейблов на все наборы: лейбл означает один и тот же путь, кто бы его ни
// поставлял, и имена в словаре — наши собственные (сторожит locales.test.ts)
const RAILTYPE_NAMES: Record<string, Record<string, string>> = { ru: railtypesRu };

/** Translated cargo name, or the English one from the data. */
export function cargoName(cargo: { id: string; name: string } | null | undefined): string {
  if (!cargo) return '';
  const { locale } = useLocaleStore.getState();
  return CARGO_NAMES[locale]?.[cargo.id] ?? cargo.name;
}

/** Unit of measure the data spells out in words: litres, tonnes, crates… */
export function cargoUnits(units: string | null | undefined): string {
  if (!units) return '';
  const { locale } = useLocaleStore.getState();
  return CARGO_UNITS[locale]?.[units] ?? units;
}

/** Industry name; economies may rename an industry, hence the optional override. */
export function industryName(
  industry: { id: string; name: string; name_by_economy?: Record<string, string> } | null | undefined,
  economyId?: string,
): string {
  if (!industry) return '';
  const { locale } = useLocaleStore.getState();
  const translated = INDUSTRY_NAMES[locale]?.[industry.id];
  if (translated) return translated;
  return (economyId ? industry.name_by_economy?.[economyId] : undefined) ?? industry.name;
}

/**
 * Does this vehicle answer to what the player typed? Shared, because the catalogue and the
 * optimizer each offer this search and must agree on what matches.
 */
export function matchesTrainName(train: { name: string }, needle: string): boolean {
  return train.name.toLowerCase().includes(needle.toLowerCase());
}

/**
 * The roster's name as it is written wherever one is named — the settings picker and the
 * savegame diff both read it here, so a set added later cannot end up spelled two ways or
 * missed in one of them. Set names are proper nouns and stay untranslated; only "vanilla"
 * is a word of ours.
 */
export function trainSetName(set: TrainSet): string {
  switch (set) {
    case 'iron_horse': return 'Iron Horse';
    case 'vanilla': return t('settings.trainSetVanilla');
  }
}

/** Track type name, as the set or the game calls it. */
export function railtypeName(
  railtype: { label: string; name: string } | null | undefined,
): string {
  if (!railtype) return '';
  const { locale } = useLocaleStore.getState();
  return RAILTYPE_NAMES[locale]?.[railtype.label] ?? railtype.name;
}

/**
 * Track types with the labels a picker shows, which are their names except where a set
 * gives two types the same one — Iron Horse names both its high speed tracks "Dedicated
 * High Speed Railway". A menu of identical entries is no choice at all, so a name shared
 * by several types says which is which by the one thing that tells them apart: whether
 * the track carries wires. The suffix is ours; the set has no word for it.
 */
export function railtypeOptions<T extends { label: string; name: string; catenary: boolean }>(
  railtypes: readonly T[],
): { railtype: T; name: string }[] {
  const named = railtypes.map((railtype) => ({ railtype, name: railtypeName(railtype) }));
  const shared = repeated(named.map((option) => option.name));
  const told = named.map((option) => {
    if (!shared.has(option.name)) return option;
    const suffix = t(
      option.railtype.catenary ? 'railtype.electrified' : 'railtype.unelectrified',
    );
    return { ...option, name: `${option.name} (${suffix})` };
  });
  // wires tell today's namesakes apart, but a set could name two tracks alike that agree on
  // them too. The label is what the game itself falls back on, and a menu of identical
  // entries is no choice at all, so it is better than leaving them indistinguishable.
  const stillShared = repeated(told.map((option) => option.name));
  return told.map((option) =>
    stillShared.has(option.name)
      ? { ...option, name: `${option.name} [${option.railtype.label}]` }
      : option,
  );
}

/** The names that more than one entry carries — the ones a picker has to tell apart. */
function repeated(names: readonly string[]): Set<string> {
  const seen = new Set<string>();
  const twice = new Set<string>();
  for (const name of names) {
    if (seen.has(name)) twice.add(name);
    seen.add(name);
  }
  return twice;
}

/**
 * Passengers and mail head every cargo list in the game itself, so they stay
 * pinned to the top instead of falling wherever the alphabet puts them.
 */
const PINNED_CARGOS = ['passengers', 'mail'];

/**
 * Cargo pickers read as a list, so order them by what the user actually sees.
 * Takes the locale as an argument rather than reading the store: callers memoise
 * the sorted list, and this way the locale is a real dependency of that memo.
 */
export function sortCargos<T extends { id: string; name: string }>(
  cargos: T[],
  locale: Locale,
): T[] {
  const names = CARGO_NAMES[locale] ?? {};
  const collator = new Intl.Collator(LOCALES[locale].numbers);
  const rank = (id: string) => {
    const pinned = PINNED_CARGOS.indexOf(id);
    return pinned === -1 ? PINNED_CARGOS.length : pinned;
  };
  return [...cargos].sort(
    (a, b) =>
      rank(a.id) - rank(b.id) ||
      collator.compare(names[a.id] ?? a.name, names[b.id] ?? b.name),
  );
}

/**
 * Node labels in the FIRS chain graph. A graphviz node id is either a cargo label
 * (ACID) or an industry id (coal_mine); cargo labels are resolved to a cargo id
 * through the dataset. Anything unknown keeps its English label.
 */
export function localiseDot(dot: string): string {
  const { locale } = useLocaleStore.getState();
  const cargos = CARGO_NAMES[locale] ?? {};
  const industries = INDUSTRY_NAMES[locale] ?? {};
  if (!Object.keys(cargos).length && !Object.keys(industries).length) return dot;
  const translate = (id: string) => {
    const cargo = cargoByLabel.get(id);
    return (cargo ? cargos[cargo.id] : undefined) ?? industries[id];
  };
  return dot.replace(/"([^"]+)" \[([^\]]*?)label="([^"]*)"/g, (full, id, attrs) => {
    const name = translate(id);
    return name ? `"${id}" [${attrs}label="${name}"` : full;
  });
}
