"""Русские имена машин xUSSR: lang/russian.lng набора -> web/src/i18n/trains_xussr.ru.json.

Тот же механизм, что словари грузов и типов путей: словарь генерируется, руками не
правится, дрейф ловит make check-i18n. Ключ — id машины; строки с параметрами
({UNSIGNED_WORD}) собираются так же, как английские имена в extract_xussr.py.
Машина без русской строки в словарь не пишется — интерфейс показывает английское
имя, а полноту стережёт locales.test.ts.
"""
import os
import re
import sys

from common import I18N_DIR, load_json, write_dictionary
from extract_xussr import lang_strings


def render(text, params):
    for value in params:
        text = text.replace("{UNSIGNED_WORD}", str(value), 1)
    return re.sub(r"\{[A-Z_]+\}", "", text)


def main(check=False):
    russian = lang_strings("russian.lng")
    payload_data = load_json("xussr_trains.json")
    items = payload_data["items"]
    names = {}
    for item in items:
        text = russian.get(item["string_id"])
        if text is None:
            # модельные номера (STR_MODEL_NUMBER*: «12-132») русская локаль набора
            # не дублирует — они языконезависимы, имя совпадает с английским
            if item["string_id"].startswith("STR_MODEL_NUMBER"):
                names[item["id"]] = item["name"]
            continue
        names[item["id"]] = render(text, item["name_params"])
    # пути того же набора — тем же словарём: ключ, как в railtypes.ru.json, лейбл;
    # скрытые RAIL/ELRL уже названы ванильным словарём и здесь не повторяются
    railtypes = {}
    for railtype in payload_data["meta"]["railtypes"]:
        text = russian.get(railtype["string_id"])
        if text is not None and railtype["label"] not in ("RAIL", "ELRL"):
            railtypes[railtype["label"]] = render(text, [])
    payload = {
        "": "Generated by pipeline/extract_xussr_ru.py from the set's own Russian "
            "locale (vendor/xussrset/lang/russian.lng) — do not edit by hand",
        "trains": names,
        "railtypes": railtypes,
    }
    ok = write_dictionary(os.path.join(I18N_DIR, "trains_xussr.ru.json"), payload, check)
    if not ok:
        sys.exit(1)


if __name__ == "__main__":
    main(check="--check" in sys.argv)
